force-app/main/default/objects/Form__c/Form__c.object-meta.xml
<CustomObject>
    <label>Form</label>
    <nameField>
        <displayFormat>F-{YYYY}{MM}-{0}</displayFormat>
        <label>Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FormQuestion__c/FormQuestion__c.object-meta.xml
<CustomObject>
    <label>Form Question</label>
    <nameField>
        <label>Form Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FormQuestion__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <referenceTo>Form__c</referenceTo>
    <relationshipLabel>Form Questions</relationshipLabel>
    <relationshipName>Form_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FormQuestion__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Form Questions</relationshipLabel>
    <relationshipName>Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QuestionController.cls
public with sharing class QuestionController {
    
    @AuraEnabled(cacheable=true)
    public static List<Question__c> getQuestionsByForm(String formId) {
        List<FormQuestion__c> formQuestions = [SELECT Question__r.Id FROM FormQuestion__c WHERE Form__c = :formId];
        
        Set<Id> questionIds = new Set<Id>();
        for (FormQuestion__c fq : formQuestions) {
            questionIds.add(fq.Question__r.Id);
        }
        
        return [SELECT Id, Title__c, Description__c FROM Question__c WHERE Id IN :questionIds];
    }
    
    @AuraEnabled
    public static Id createQuestion(String questionData) {
        Map<String, Object> questionDataMap = (Map<String, Object>) JSON.deserializeUntyped(questionData);
        String formId = (String) questionDataMap.get('FormId');
        
        // Create Question__c record
        Question__c newQuestion = new Question__c();
        newQuestion.Title__c = (String) questionDataMap.get('Title');
        newQuestion.Description__c = (String) questionDataMap.get('Description');
        insert newQuestion;
        
        // Create FormQuestion__c junction record
        FormQuestion__c formQuestion = new FormQuestion__c();
        formQuestion.Form__c = formId;
        formQuestion.Question__c = newQuestion.Id;
        insert formQuestion;
        
        return newQuestion.Id;
    }
    
    @AuraEnabled
    public static Question__c getQuestionById(String questionId) {
        return [SELECT Id, Title__c, Description__c FROM Question__c WHERE Id = :questionId];
    }
    
    @AuraEnabled
    public static void updateQuestion(String questionData) {
        Map<String, Object> questionDataMap = (Map<String, Object>) JSON.deserializeUntyped(questionData);
        Question__c existingQuestion = new Question__c(Id = (String) questionDataMap.get('Id'));
        existingQuestion.Title__c = (String) questionDataMap.get('Title');
        existingQuestion.Description__c = (String) questionDataMap.get('Description');
        update existingQuestion;
    }
    
    @AuraEnabled
    public static void deleteQuestion(String questionId) {
        Question__c questionToDelete = new Question__c(Id = questionId);
        delete questionToDelete;
    }
    
}